### ISSUE TITLE
Change random generating of options

### ISSUE THREAD

**Issue by JobLabLSU** [dmarkant/SamplingParadigmDFE#1]
I am currently customizing this experiment and would like to change from randomly generating options...to where I can customize which options are pulled from the option set. Any insight?

**Comment by dmarkant** [comment]
Do you mean that you want to present the options in a fixed order, rather than draw a random subset (as in https://github.com/dmarkant/SamplingParadigmDFE/blob/master/static/js/task.js#L32)? 

If so, then you would want to first define the order, then sample the corresponding option set at each index. That might look something like this (using the map function from underscore.js):

```
var indices = [2, 1, 4];
var OPTSETS_SAMPLED = _.map(indices, function(i) { return OPTSETS[i]; });
```

Is that helpful?

**Comment by JobLabLSU** [comment]
Thank you for your reply and yes, that is exactly what I am hoping to achieve. You mentioned that I should first "define the order," should that be done under "utils.js" or "task.js" (please excuse my lack of knowledge on this, I am new to coding)

**Comment by dmarkant** [comment]
By "define the order" I was referring to the first line of code in my previous comment -- the `indices` variable tells you the ordering of option sets, where each number is an index pointing to one of the option sets contained in the `OPTSETS` array (which itself is based on the .csv file). Keeping in mind that indices start at 0 in javascript, that means that in the example above the 3rd set would occur first, followed by the 2nd set, followed by the 5th set. So you can change the indices to whatever order you want the different sets to occur in.

Alternatively, if you've already ordered option sets in right sequence in the .csv file, then you could replace all that with `var OPTSETS_SAMPLED = OPTSETS;` and they should occur in the same sequence.

Hope that helps!

**Comment by JobLabLSU** [comment]
That helps. I appreciate your help, thanks so much!
